#!/usr/bin/env python3
import json,pathlib,re
O='/var/minis/workspace/grimdawn-assistant/data_js/locations.js'
acts={
1:[('埋葬洞穴（埋葬山丘）','Burial Hill','供奉','普通：虚化水晶；精英/终极：虚化碎片','击杀复生者基佐格后，沿地图下方中路走到尽头。'),('恶魔含水层','Devil’s Aquifer','供奉','普通：虚化水晶；精英/终极：虚化碎片','从恶魔十字下方进入含水层，神龛在地图最东侧。'),('雾岸洞穴','Foggy Bank','战斗','清理腐化怪物','雾岸北行途中进入有两个入口的洞穴，靠近北入口。'),('淹没通道','Flooded Passage','战斗','清理虚化怪物','通往尸妖泥沼的地下通道北端、出口附近。'),('伯尔维治郊外埋葬洞穴','Burrwitch Outskirts','供奉','普通：虚化水晶；精英/终极：虚化碎片','离开淹没通道后，在有两个入口的埋葬洞穴内。'),('东部沼泽','East Marsh','供奉','普通：破损之爪；精英/终极：断裂之爪','带炸药、废料和铁币修桥后进入东部沼泽。'),('伯尔维治庄园','Burrwitch Estates','战斗','清理虚化怪物','露天区域西北角，靠地图最西侧兴趣点。'),('神圣山丘','Hallowed Hill','供奉','精英/终极：虚化碎片','隐藏区域神圣山丘；普通难度不提供。'),('典狱长实验室','Warden’s Lab','供奉','普通：虚化水晶；精英/终极：虚化碎片','地下运输区可破坏墙附近北侧。'),('隐藏之路','The Hidden Path','供奉','终极：裂隙之石','携带炸药清除路障；隐藏之路任务区。'),('三巫神殿','Temple of the Three','战斗','清理腐化怪物','收齐隐藏之路三块符石后开门。')],
2:[('阿尔科维亚山麓','Arkovian Foothills','战斗','清理腐化怪物','沿主线进入山麓后探索地图边缘。'),('岩石海岸','Rocky Coast','供奉','普通：冰封之心；精英/终极：复仇怨灵','山麓附近岩石海岸支路。'),('克隆利藏身处','Cronley’s Hideout','供奉','普通：回收铠甲片；精英/终极：废料+回收铠甲片','克隆利藏身处内部支路。'),('古安克维亚','Old Arkovia','战斗','清理腐化怪物','古安克维亚露天废墟。'),('阿尔科维亚地下城','Arkovian Undercity','供奉','普通：冰冷石；精英/终极：寒冰石','地下城内探索岔路。'),('苦痛阶梯','Steps of Torment','战斗','清理腐化怪物','苦痛阶梯副本内。'),('贫瘠高地','Barren Highlands','供奉','普通：抛光翡翠；精英/终极：灌银粉','贫瘠高地边缘支路。')],
3:[('山脉深渊','Mountain Deeps','战斗','清理腐化怪物','穿越山脉深渊时探索支路。'),('遗忘深渊','Forgotten Depths','供奉','普通：锯齿尖刺；精英/终极：凶残颚骨','遗忘深渊内部。'),('暴君要塞','Tyrant’s Hold','供奉','普通：灼热余烬；精英/终极：附魔燧石','暴君要塞内部支路。'),('大火','The Conflagration','战斗','清理虚化怪物','大火区域内。'),('瓦尔伯港','Port Valbury','战斗','清理虚化怪物','骸骨钥匙副本瓦尔伯港内。'),('感染农田','Infested Farms','供奉','普通：突变脓液；精英/终极：突变鳞片','霍姆斯特德周边感染农田。'),('迷失者洞穴','Den of the Lost','战斗','清理腐化怪物','隐藏区域迷失者洞穴。'),('血森林','Blood Grove','供奉','普通：冥煞封印；精英/终极：冥煞封印+神圣裹布','血森林区域。'),('碎石采石场','Stonerend Quarry','战斗','清理腐化怪物','血森林附近采石场支路。'),('黑谷村','Darkvale Village','战斗','清理冥煞怪物','黑谷村内主线沿途。')],
4:[('阿斯特堪山谷','Asterkarn Valley','供奉','普通：破裂磁石；精英/终极：琥珀','阿斯特堪山谷露天区域。'),('诅咒者墓穴','Tomb of the Damned','供奉','普通：远古之心；精英：远古之心+冥煞之血；终极再加污染大脑','执政官巴索勒姆墓穴东北进入隐藏墓穴。'),('莫格卓根神龛','Mogdrogen’s Shrine','任务','远古之心 + 战斗','流浪者声望尊敬后接「罗瓦里遗产」；完成两个冥煞裂隙任务。'),('大墓地','Necropolis','战斗','清理腐化怪物','大墓地区域内。'),('黑色坟墓','The Black Sepulcher','供奉','普通：翻腾之血；精英/终极：神圣之牙','大墓地附近黑色坟墓。'),('守望者墓穴','Tomb of the Watchers','战斗','清理腐化怪物','大墓地主线路径。'),('混沌堡垒','Bastion of Chaos','战斗','清理冥煞怪物','骸骨钥匙副本混沌堡垒内。'),('不朽圣殿','Sanctum of the Immortal','供奉','终极：骸骨钥匙','完成黛拉与德里维斯隐藏任务后开启传送门。')],
5:[('幽暗森林','Gloomwald','战斗','清理腐化怪物','幽暗森林主线区域。'),('远古树林','Ancient Grove','战斗','清理腐化怪物','骸骨钥匙副本远古树林内。'),('远古洞穴','Den of the Ancient','供奉','终极：3×乌苟登之花','远古树林/乌苟登地区隐藏洞穴。'),('乌苟登沼泽','Ugdenbog','供奉','普通：灵质；精英/终极：复仇怨灵','乌苟登沼泽支路。'),('巴罗霍尔姆矿井','Barrowholm Mine','战斗','清理腐化怪物','巴罗霍尔姆任务相关矿井。'),('虚空边缘','Void’s Edge','战斗','清理冥煞怪物','虚空边缘裂隙区域。')],
6:[('马尔茅斯','Malmouth','供奉','普通：虚化碎片；精英/终极：虚化钢弹药','马尔茅斯城区探索。'),('被劫掠的灯塔','Ransacked Lighthouse','战斗','清理腐化怪物','马尔茅斯外围灯塔。'),('皇冠高地','Crown Hill','战斗','清理虚化怪物','皇冠高地主线区域。'),('感染巢穴','The Infestation','战斗','清理腐化怪物','皇冠高地附近感染区。'),('天选者圣殿（洛卡尔）','Sanctum of the Chosen','供奉','终极：骸骨钥匙','完成洛卡尔隐藏任务后开启传送门。')],
7:[('奥西尔神殿','Temple of Osyr','战斗','清理腐化怪物','遗忘之神主线神殿。'),('寇瓦克绿洲','Korvan Oasis','供奉','普通：破损甲壳；精英/终极：硬化甲壳','寇瓦克绿洲区域。'),('凯兰码头','Cairan Docks','战斗','清理腐化怪物','码头区域。'),('风蚀废墟','Sandblown Ruins','战斗','清理腐化怪物','沙漠废墟支路。'),('霍兰圣所','Sanctuary of Horran','战斗','清理腐化怪物','霍兰圣所内部。'),('阿比德废墟','Ruins of Abyd','供奉','普通：冰冷石+破裂磁石+灼热余烬；精英/终极：光芒宝石','阿比德废墟区域。'),('天选者山谷','Valley of the Chosen','战斗','清理腐化怪物','三神教派主线区域。'),('向日尖塔','Sunward Spire','战斗','清理腐化怪物','向日尖塔内部。'),('邪阳墓穴','Tomb of the Eldritch Sun','战斗','清理腐化怪物','邪阳墓穴内。'),('异教徒墓穴','Tomb of the Heretic','战斗','清理腐化怪物','骸骨钥匙副本异教徒墓穴。'),('碎境华庭','Splendors of the Shattered Realm','供奉','普通：虚化水晶；精英/终极：天界莲花','三巫神秘会找传送门守护者马赞，完成碎境第1层并在奖励房领取。'),('天选者圣殿（箱子）','Sanctum of the Chosen','供奉','终极：骸骨钥匙','完成 Crate of Entertainment 隐藏任务后开启传送门。')]
}
items=[]
for act,ls in acts.items():
 for i,(zh,en,typ,req,how) in enumerate(ls,1):
  q=en.replace(' ','%20').replace('’',"%27")
  items.append({'id':f'shrine-{act}-{i}','category':'shrine','act':act,'nameZh':zh,'nameEn':en,'typeZh':typ,'requirement':req,'howToFind':how,'dlc':'本体' if act<=4 else ('灰烬之马尔茅斯' if act<=6 else '遗忘之神'),'mapUrl':'https://www.grimtools.com/map/?search='+q,'sourceUrl':'https://steamcommunity.com/sharedfiles/filedetails/?id=562989376','keywords':f'神龛 星座点 devotion shrine 第{act}章 {zh} {en} {typ} {req} {how}'})
# 搜索入口还覆盖 NPC/怪物/容器，运行时由 app.js 与 directory.js 合并
D={'version':14,'updatedFor':'Steam 指南 v1.2.0.2 + GrimTools World Map；阿斯特肯之牙新增区域等待官方清单稳定后再补','note':'59 个已验证神龛地点；一座神龛通常给 1 星座点，最多 55。地点按钮以 GrimTools 世界地图搜索打开。','categories':[{'id':'all','name':'全部地点'},{'id':'shrine','name':'神龛'},{'id':'npc','name':'NPC/商人'},{'id':'monster','name':'专属怪'},{'id':'container','name':'宝箱/容器'}],'shrines':items,'sources':[{'name':'Steam Devotion Shrines','url':'https://steamcommunity.com/sharedfiles/filedetails/?id=562989376'},{'name':'GrimTools World Map','url':'https://www.grimtools.com/map/'}]}
pathlib.Path(O).write_text('window.GD_LOCATION_GUIDE = '+json.dumps(D,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
print('wrote shrines',len(items))
