const KEY='travel-ledger-2026-shanghai-v1';
const seed={trip:'上海迪士尼之旅',destination:'重庆 ⇄ 上海',budget:0,start:'2026-07-30',end:'2026-08-08',members:'刘伟,张倩,张艳',entries:[
{id:'flight1276',date:'2026-07-28',time:'12:24',cat:'交通',note:'张倩往返机票（刘伟个人承担）',payer:'刘伟',amount:1276,splitType:'personal',shares:{刘伟:1276,张倩:0,张艳:0}},
{id:'disney193890',date:'2026-07-28',time:'12:23',cat:'游玩',note:'上海迪士尼3人门票',payer:'刘伟',amount:1938.90,splitType:'custom',shares:{刘伟:1292.60,张倩:0,张艳:646.30}}
]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||seed;
if(!state.entries.some(x=>x.id==='hotel179')){state.entries.push({id:'hotel179',date:'2026-07-28',time:'12:56',cat:'住宿',note:'Mosa摩萨德酒店（上海浦东机场店）·待到店支付',payer:'刘伟',amount:179,status:'pending',splitType:'equal',shares:{刘伟:119.33,张倩:0,张艳:59.67}})}
let hotel=state.entries.find(x=>x.id==='hotel179');if(hotel){hotel.payer='刘伟';hotel.splitType='equal';hotel.shares={刘伟:119.33,张倩:0,张艳:59.67}}
if(!state.entries.some(x=>x.id==='taxi5978')){state.entries.push({id:'taxi5978',date:'2026-07-30',time:'07:37',cat:'交通',note:'下飞机打车·T3特快（郭师傅·沪BD66087）',payer:'刘伟',amount:59.78,status:'paid',splitType:'equal',shares:{刘伟:39.85,张倩:0,张艳:19.93}})}
state.entries=state.entries.filter(x=>x.id!=='luckin3390');
if(!state.entries.some(x=>x.id==='kfc4940')){state.entries.push({id:'kfc4940',date:'2026-07-31',time:'09:16',cat:'餐饮',note:'KFC祝桥餐厅·早餐（咖啡+饭团+小笼包餐+粥套餐+大神卡）',payer:'刘伟',amount:49.40,status:'paid',splitType:'equal',shares:{刘伟:32.93,张倩:0,张艳:16.47}})}
if(!state.entries.some(x=>x.id==='taxi2020')){state.entries.push({id:'taxi2020',date:'2026-07-31',time:'09:19',cat:'交通',note:'早上打车·摩萨德酒店→天和夜排档（张师傅·沪C2M582）',payer:'刘伟',amount:20.20,status:'paid',splitType:'equal',shares:{刘伟:13.47,张倩:0,张艳:6.73}})}
if(!state.entries.some(x=>x.id==='familymart5860')){state.entries.push({id:'familymart5860',date:'2026-07-31',time:'09:40',cat:'购物',note:'全家零食购物（微信两笔56.60+2.00）',payer:'刘伟',amount:58.60,status:'paid',splitType:'equal',shares:{刘伟:39.07,张倩:0,张艳:19.53}})}
if(!state.entries.some(x=>x.id==='locker6000')){state.entries.push({id:'locker6000',date:'2026-07-31',time:'10:50',cat:'游玩',note:'迪士尼存包（司福特博格）·柜号1618',payer:'刘伟',amount:60.00,status:'paid',splitType:'equal',shares:{刘伟:40.00,张倩:0,张艳:20.00},lockerNo:'1618'})}
let locker=state.entries.find(x=>x.id==='locker6000');if(locker){locker.note='迪士尼存包（司福特博格）·柜号1618';locker.lockerNo='1618'}
state.entries=state.entries.filter(x=>x.id!=='luckin3390'&&x.id!=='drink6000'&&x.id!=='disneyDrink2500');
if(!state.entries.some(x=>x.id==='disneydrink2500')){state.entries.push({id:'disneydrink2500',date:'2026-07-31',time:'17:38',cat:'餐饮',note:'迪士尼园区买饮料（FL Stadium自动售货机）',payer:'刘伟',amount:25.00,status:'paid',splitType:'equal',shares:{刘伟:16.67,张倩:0,张艳:8.33}})}
if(!state.entries.some(x=>x.id==='taxidisney5783')){state.entries.push({id:'taxidisney5783',date:'2026-07-31',time:'09:28',cat:'交通',note:'早上打车→迪士尼停车场（施师傅·沪ABZ7068·14km）',payer:'刘伟',amount:57.83,status:'paid',splitType:'equal',shares:{刘伟:38.55,张倩:0,张艳:19.28}})}
let toDisney=state.entries.find(x=>x.id==='taxidisney5783');if(toDisney){toDisney.time='09:28';toDisney.date='2026-07-31';toDisney.note='早上打车→迪士尼停车场（施师傅·沪ABZ7068·14km）'}
if(!state.entries.some(x=>x.id==='hotel18500')){state.entries.push({id:'hotel18500',date:'2026-07-31',time:'20:46',cat:'住宿',note:'怡致酒店（上海祝桥浦东机场店）·今晚住宿·待支付',payer:'刘伟',amount:185.00,status:'pending',splitType:'equal',shares:{刘伟:123.33,张倩:0,张艳:61.67}})}
if(!state.entries.some(x=>x.id==='water1400')){state.entries.push({id:'water1400',date:'2026-07-31',time:'21:33',cat:'餐饮',note:'今晚买水（阿意）',payer:'刘伟',amount:14.00,status:'paid',splitType:'equal',shares:{刘伟:9.33,张倩:0,张艳:4.67}})}
if(!state.entries.some(x=>x.id==='dinner6900')){state.entries.push({id:'dinner6900',date:'2026-07-31',time:'22:28',cat:'餐饮',note:'晚餐（姜师傅淮南牛肉汤51 + 快乐鸡蛋饼18）',payer:'刘伟',amount:69.00,status:'paid',splitType:'equal',shares:{刘伟:46.00,张倩:0,张艳:23.00}})}
if(!state.entries.some(x=>x.id==='water400')){state.entries.push({id:'water400',date:'2026-07-31',time:'22:57',cat:'餐饮',note:'饭后喝水（慧掌柜）',payer:'刘伟',amount:4.00,status:'paid',splitType:'equal',shares:{刘伟:2.67,张倩:0,张艳:1.33}})}
if(!state.entries.some(x=>x.id==='hotel55428')){state.entries.push({id:'hotel55428',date:'2026-08-01',time:'12:42',cat:'住宿',note:'7天酒店（新7天·上海西藏南路地铁站店）·高级双床房·待支付',payer:'刘伟',amount:554.28,status:'pending',splitType:'equal',shares:{刘伟:369.52,张倩:0,张艳:184.76}})}
if(!state.entries.some(x=>x.id==='taxi4326')){state.entries.push({id:'taxi4326',date:'2026-08-01',time:'12:51',cat:'交通',note:'中午打车（周师傅·沪ADW3801·12km）',payer:'刘伟',amount:43.26,status:'paid',splitType:'equal',shares:{刘伟:28.84,张倩:0,张艳:14.42}})}
if(!state.entries.some(x=>x.id==='gebi7960')){state.entries.push({id:'gebi7960',date:'2026-08-02',time:'10:40',cat:'餐饮',note:'隔壁妈妈（美团）·刘伟与张艳平分·张倩未吃',payer:'刘伟',amount:79.60,status:'paid',splitType:'custom',shares:{刘伟:39.80,张倩:0,张艳:39.80}})}
if(!state.entries.some(x=>x.id==='hotel40880')){state.entries.push({id:'hotel40880',date:'2026-08-02',time:'15:55',cat:'住宿',note:'上海松江体育中心亚朵酒店·高级双·1晚·支付宝担保',payer:'刘伟',amount:408.80,status:'paid',splitType:'equal',shares:{刘伟:272.53,张倩:0,张艳:136.27},orderNo:'3315854964356024895'})}
localStorage.setItem(KEY,JSON.stringify(state));
const cats={餐饮:'<img class="catIconImg" src="icons/category-food.svg?v=20260807-icons1" alt="餐饮">',交通:'<img class="catIconImg" src="icons/category-transport.svg?v=20260807-icons1" alt="交通">',住宿:'<img class="catIconImg" src="icons/category-stay.svg?v=20260807-icons1" alt="住宿">',酒店:'<img class="catIconImg" src="icons/category-stay.svg?v=20260807-icons1" alt="住宿">',游玩:'<img class="catIconImg" src="icons/category-play.svg?v=20260807-icons1" alt="游玩">',购物:'<img class="catIconImg" src="icons/category-shop.svg?v=20260807-icons1" alt="购物">',其他:'<img class="catIconImg" src="icons/category-other.svg?v=20260807-icons1" alt="其他">'};
const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const members=()=>state.members.split(/[,，、]/).map(x=>x.trim()).filter(Boolean);
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function shareText(x){if(['personal','family'].includes(x.splitType))return '刘伟家庭承担';if(['equal','common'].includes(x.splitType))return '家庭2/3 · 张艳1/3';if(x.splitType==='half')return '刘伟 · 张艳各1/2';if(x.splitType==='custom')return '指定分摊';return '未指定分摊'}
function render(){let total=state.entries.reduce((s,x)=>s+Number(x.amount),0),dates=[...new Set(state.entries.map(x=>x.date))];tripTitle.textContent=state.trip;tripMeta.textContent=state.destination||'随手记，放心玩';document.querySelector('#total').textContent=money(total).slice(1);count.textContent=state.entries.length+'笔';dailyAvg.textContent=money(dates.length?total/dates.length:0);if(state.budget){remaining.textContent=money(state.budget-total);budgetTag.textContent=`预算 ${money(state.budget)}`;progressBar.style.width=Math.min(100,total/state.budget*100)+'%'}else{remaining.textContent='—';budgetTag.textContent='未设置预算';progressBar.style.width='0'}let sorted=[...state.entries].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)),groups={};sorted.forEach(x=>(groups[x.date]??=[]).push(x));let ds=Object.keys(groups);dateRange.textContent=ds.length?`${ds.at(-1)} 至 ${ds[0]}`:'还没有记录';list.innerHTML=ds.length?ds.map(d=>`<div class="day"><div class="dayHead"><span>${fmtDate(d)}</span><b>${money(groups[d].reduce((s,x)=>s+Number(x.amount),0))}</b></div>${groups[d].map(x=>`<div class="item" onclick="showEntry('${x.id}')"><div class="emoji">${cats[x.cat]||'✨'}</div><div><h3>${esc(x.note||x.cat)}</h3><p>${x.payer||'刘伟'}支付 · ${shareText(x)}</p></div><strong>-${money(x.amount)}</strong></div>`).join('')}</div>`).join(''):'<div class="empty"><b>🧳</b>旅程还没开销</div>'}
function fmtDate(d){let x=new Date(d+'T00:00:00');return `${x.getMonth()+1}月${x.getDate()}日 · ${['周日','周一','周二','周三','周四','周五','周六'][x.getDay()]}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function modal(html){modalBody.innerHTML=html;document.querySelector('#modal').classList.add('show')}
function closeModal(){document.querySelector('#modal').classList.remove('show')}
function openEntry(cat='餐饮'){let now=new Date(),date=now.toISOString().slice(0,10),time=now.toTimeString().slice(0,5);modal(`<h2>记一笔支出</h2><form onsubmit="addEntry(event)"><div class="field"><label>金额</label><input name="amount" inputmode="decimal" type="number" step="0.01" min="0.01" placeholder="0.00" required></div><div class="row"><div class="field"><label>分类</label><select name="cat">${Object.keys(cats).map(x=>`<option ${x==cat?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>付款人</label><select name="payer">${members().map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></div><div class="field"><label>费用归属</label><select name="splitType"><option value="equal">共同分摊（刘伟家庭2/3、张艳1/3）</option><option value="personal">刘伟家庭承担</option><option value="custom">指定金额分摊</option></select></div><div class="field"><label>备注</label><input name="note" placeholder="例如：机场打车"></div><div class="row"><div class="field"><label>日期</label><input name="date" type="date" value="${date}" required></div><div class="field"><label>时间</label><input name="time" type="time" value="${time}" required></div></div><button class="save">保存这笔支出</button></form>`)}
function addEntry(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target)),amount=Number(o.amount),ms=members();o.id=Date.now().toString(36);o.amount=amount;if(o.splitType==='equal'){let sister=+(amount/3).toFixed(2);o.payer='刘伟';o.shares={刘伟:+(amount-sister).toFixed(2),张倩:0,张艳:sister}}else if(o.splitType==='personal'){o.shares={};ms.forEach(m=>o.shares[m]=m===o.payer?amount:0)}else{o.splitType='unassigned';o.shares={}}state.entries.push(o);save();closeModal();toast('已记入账本')}
function showEntry(id){let x=state.entries.find(v=>v.id===id),shares=x.shares||{},receipt=x.receipt?`<h3 class="receiptTitle">支付凭证</h3><button class="receiptCard" onclick="viewReceipt('${x.receipt}')"><img src="${x.receipt}" alt="${esc(x.note)}支付截图"><span>查看原图</span></button>`:`<div class="noReceipt">该账单暂未关联支付截图</div>`;modal(`<h2>${cats[x.cat]||'✨'} ${esc(x.note)}</h2><div class="hero detailHero"><div class="heroTop"><span>${shareText(x)}</span><span>${x.status==='pending'?'待支付':`${x.payer}支付`}</span></div><div class="amount"><i>¥</i><b>${money(x.amount).slice(1)}</b></div></div><h3 class="shareTitle">费用归属</h3>${members().map(m=>`<div class="item"><div class="emoji">${m.slice(-1)}</div><div><h3>${m}</h3><p>${m==='张倩'?'刘伟老婆':m==='刘伟'?'本人':'同行人'}</p></div><strong>${money(shares[m]||0)}</strong></div>`).join('')}${receipt}<button class="save danger" onclick="deleteEntry('${x.id}')">删除这笔记录</button>`)}
function viewReceipt(src){modal(`<h2>支付凭证</h2><button class="receiptFull" onclick="window.open('${src}','_blank')"><img src="${src}" alt="支付截图"><span>点按查看原图</span></button>`)}
function deleteEntry(id){if(confirm('删除这笔记录？')){state.entries=state.entries.filter(x=>x.id!==id);save();closeModal()}}
function openSettings(){modal(`<h2>行程设置</h2><form onsubmit="setTrip(event)"><div class="field"><label>行程名称</label><input name="trip" value="${esc(state.trip)}" required></div><div class="field"><label>目的地</label><input name="destination" value="${esc(state.destination)}"></div><div class="field"><label>总预算（元）</label><input name="budget" type="number" min="0" value="${state.budget||''}"></div><div class="row"><div class="field"><label>开始日期</label><input name="start" type="date" value="${state.start}"></div><div class="field"><label>结束日期</label><input name="end" type="date" value="${state.end}"></div></div><div class="field"><label>同行成员</label><input name="members" value="${esc(state.members)}"></div><button class="save">保存行程</button></form>`)}
function setTrip(e){e.preventDefault();Object.assign(state,Object.fromEntries(new FormData(e.target)));state.budget=Number(state.budget||0);save();closeModal();toast('行程已更新')}
function categoryOf(x){return x.cat==='酒店'?'住宿':x.cat}
function subcategoryOf(x){let n=x.note||'',c=categoryOf(x);if(c==='交通'){if(/打车|网约车|出租车|滴滴|车费/.test(n))return '打车';if(/高铁|火车|G\d+/.test(n))return '高铁/火车';if(/机票|飞机|航班/.test(n))return '机票/飞机';return '其他交通'}if(c==='餐饮'){if(/麦当劳/.test(n))return '麦当劳';if(/肯德基|KFC/i.test(n))return '肯德基';if(/寿司/.test(n))return '寿司';if(/火锅/.test(n))return '火锅';return '其他餐饮'}if(c==='住宿'){if(/如家/.test(n))return '如家';if(/亚朵/.test(n))return '亚朵';if(/7天/.test(n))return '7天酒店';return '其他住宿'}return c}
function statSum(es){return es.reduce((s,x)=>s+Number(x.amount||0),0)}
function statShares(es){return {family:es.reduce((s,x)=>s+Number(x.shares?.刘伟||0)+Number(x.shares?.张倩||0),0),sister:es.reduce((s,x)=>s+Number(x.shares?.张艳||0),0)}}
function statEntries(cat,sub=''){return state.entries.filter(x=>categoryOf(x)===cat&&(!sub||subcategoryOf(x)===sub))}
function statRow(label,es,icon='✨',onclick=''){return `<button class="statRow" ${onclick?`onclick="${onclick}"`:''}><span class="statIcon">${icon}</span><span class="statMain"><b>${esc(label)}</b><small>${es.length}笔</small></span><strong>${money(statSum(es))}</strong><span class="statArrow">›</span></button>`}
function openStats(){let total=statSum(state.entries),sh=statShares(state.entries),map={};state.entries.forEach(x=>{let c=categoryOf(x);(map[c]??=[]).push(x)});let order=['餐饮','交通','住宿','游玩','购物','其他'],catsList=[...order,...Object.keys(map).filter(x=>!order.includes(x))].filter(x=>map[x]?.length);modal(`<h2>分类统计</h2><div class="hero" style="margin:0"><div class="heroTop"><span>当前旅行总支出</span><span>${state.entries.length}笔</span></div><div class="amount"><i>¥</i><b>${money(total).slice(1)}</b></div><div class="heroStats"><div><span>家庭承担</span><b>${money(sh.family)}</b></div><div><span>张艳承担</span><b>${money(sh.sister)}</b></div><div><span>分类数</span><b>${catsList.length}类</b></div></div></div><p class="statHint">点击大分类查看明细，再点击细分类查看对应账单</p><div class="statRows">${catsList.map(c=>statRow(c,map[c],cats[c]||'✨',`openCategoryStats('${c}')`)).join('')}</div>`)}
function openCategoryStats(cat,sub=''){let es=statEntries(cat,sub),sh=statShares(es),groups={};es.forEach(x=>{let s=subcategoryOf(x);(groups[s]??=[]).push(x)});let subNames=Object.keys(groups).sort((a,b)=>statSum(groups[b])-statSum(groups[a])),back=sub?`<button class="backBtn" onclick="openCategoryStats('${cat}')">‹ ${esc(cat)}分类</button>`:`<button class="backBtn" onclick="openStats()">‹ 全部分类</button>`,title=sub?`${cat} · ${sub}`:cat,subBlock=!sub?`<h3 class="subTitle">细分类</h3><div class="statRows">${subNames.map(s=>statRow(s,groups[s],cats[cat]||'✨',`openCategoryStats('${cat}','${s}')`)).join('')}</div>`:'',detail=es.slice().sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));modal(`${back}<h2>${cats[cat]||'✨'} ${esc(title)}</h2><div class="hero" style="margin:0"><div class="heroTop"><span>${sub?'细分类总额':'分类总额'}</span><span>${es.length}笔</span></div><div class="amount"><i>¥</i><b>${money(statSum(es)).slice(1)}</b></div><div class="heroStats"><div><span>家庭承担</span><b>${money(sh.family)}</b></div><div><span>张艳承担</span><b>${money(sh.sister)}</b></div><div><span>占总支出</span><b>${(statSum(es)/Math.max(1,statSum(state.entries))*100).toFixed(2)}%</b></div></div></div>${subBlock}<h3 class="subTitle">账单明细</h3><div class="statDetail">${detail.length?detail.map(x=>`<div class="item" onclick="showEntry('${x.id}')"><div class="emoji">${cats[x.cat]||'✨'}</div><div><h3>${esc(x.note||x.cat)}</h3><p>${x.date} ${x.time} · ${x.payer||'刘伟'}支付</p></div><strong>${money(x.amount)}</strong></div>`).join(''):'<div class="empty">暂无账单</div>'}</div>`)}
function exportData(){let rows=['日期,时间,分类,备注,付款人,总金额,分摊方式,刘伟承担,张倩承担,张艳承担',...state.entries.map(x=>[x.date,x.time,x.cat,x.note,x.payer,x.amount,shareText(x),x.shares?.刘伟||0,x.shares?.张倩||0,x.shares?.张艳||0].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))],blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.trip}-分摊账单.csv`;a.click();URL.revokeObjectURL(a.href);toast('分摊账单已导出')}
function toast(s){let t=document.querySelector('#toast');t.textContent=s;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),1600)}
render();
